# Generated by Django 3.2 on 2023-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Fertilizer'), ('P', 'Pesticide'), ('S', 'Seed'), ('SP', 'Splinker'), ('PI', 'Pipe')], max_length=2),
        ),
    ]
